export const SET_USER = 'SET_USER'
export const SET_ERROR = 'SET_ERROR'
export const SET_ACTIVE_ROOM = 'SET_ACTIVE_ROOM'
export const SET_ROOMS = 'SET_ROOMS'
export const SET_USERS = 'SET_USERS'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const CLEAR_ROOM = 'CLEAR_ROOM'
